version: 2
publish: &publish
  working_directory: ~/my-app
  docker:
    - image: circleci/node:13
  steps:
    - checkout

    - run:
        name: Installing dependencies
        command: npm ci
        
    - run:
        name: Installing Expo-CLI
        command: npm install expo-cli@3.13.1
        
    - run:
        name: Login into Expo
        command: npx expo-cli login -u $EXPO_USERNAME -p $EXPO_PASSWORD

    - run:
        name: Publish to Expo
        command: npx expo-cli publish --max-workers 1
        
    - run:
        name: Trigger build
        command: npx eas-cli build --platform all --non-interactive

jobs:
  publish_to_expo_dev:
    environment:
      EXPO_RELEASE_CHANNEL: dev
    <<: *publish

  publish_to_expo_prod:
    environment:
      EXPO_RELEASE_CHANNEL: default
    <<: *publish
          
workflows:
  version: 2
  my_app:
    jobs:
      - publish_to_expo_dev:
          filters:
            branches:
              only: development
      - publish_to_expo_prod:
          filters:
            branches:
              only: staging
